version: '3.2'
services:
  qmk:
    build: ./container
    environment:
      keyboard: 'ergodox_ez,atreus,handwired/dactyl_manuform/5x6'
      layout: 'replicaJunction'

    volumes:
      # Ergodox
      - type: bind
        source: ./keyboards/ergodox
        target: /qmk_firmware/keyboards/ergodox_ez/keymaps/replicaJunction

      # Atreus
      - type: bind
        source: ./keyboards/atreus
        target: /qmk_firmware/keyboards/atreus/keymaps/replicaJunction

      # Dactyl-Manuform 5x6
      - type: bind
        source: ./keyboards/dacman_5x6
        target: /qmk_firmware/keyboards/handwired/dactyl_manuform/5x6/keymaps/replicaJunction

      # User config
      - type: bind
        source: ./user
        target: /qmk_firmware/users/replicaJunction

      # Output directory. Compiled .hex files will be placed here
      # Don't remove this one!
      - type: bind
        source: ./output
        target: /output
